import Providers from "@/components/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { checkLang } from "../../../dictonaries";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "codeReady",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params:{lang},
}: {
  children: React.ReactNode;
  params: {lang:string};
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar lang={checkLang(lang)}/>
          <div className="min-h-[calc(100vh-3.5rem)]">

          {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
