import { FC } from "react";
import { ThemeProvider } from "next-themes";
import { Metadata } from "next";
interface ProvidersProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "codeReady",
  description: "Generated by create next app",
};


const Providers: FC<ProvidersProps> = ({ children }) => {
  return (
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      {children}
    </ThemeProvider>
  );
};

export default Providers;
